import { L, type L10n } from "./i18n";

/* Shared bilingual strings for Shop, Client Portal, Affiliate Portal & Admin. */

export const PT = {
  /* General */
  signIn: L("Sign In", "সাইন ইন"),
  signOut: L("Sign Out", "সাইন আউট"),
  register: L("Create Account", "অ্যাকাউন্ট তৈরি করুন"),
  login: L("Login", "লগইন"),
  email: L("Email Address", "ইমেইল অ্যাড্রেস"),
  password: L("Password", "পাসওয়ার্ড"),
  name: L("Full Name", "পূর্ণ নাম"),
  mobile: L("Mobile Number", "মোবাইল নম্বর"),
  confirmPassword: L("Confirm Password", "পাসওয়ার্ড নিশ্চিত করুন"),
  loginTitle: L("Welcome Back", "আবার স্বাগতম"),
  loginSub: L("Login to access your account, orders and downloads.", "আপনার অ্যাকাউন্ট, অর্ডার ও ডাউনলোড অ্যাক্সেস করতে লগইন করুন।"),
  registerTitle: L("Create Your Account", "আপনার অ্যাকাউন্ট তৈরি করুন"),
  registerSub: L("Register to order services, buy digital products and manage everything in one place.", "সার্ভিস অর্ডার, ডিজিটাল প্রোডাক্ট কেনা ও সবকিছু এক জায়গায় ম্যানেজ করতে রেজিস্টার করুন।"),
  noAccount: L("Don't have an account?", "অ্যাকাউন্ট নেই?"),
  haveAccount: L("Already have an account?", "আগে থেকেই অ্যাকাউন্ট আছে?"),
  demoAccounts: L("Demo Accounts (platform preview)", "ডেমো অ্যাকাউন্ট (প্ল্যাটফর্ম প্রিভিউ)"),
  errRequired: L("This field is required.", "এই ঘরটি পূরণ করা আবশ্যক।"),
  errEmail: L("Please enter a valid email address.", "অনুগ্রহ করে একটি সঠিক ইমেইল লিখুন।"),
  errPasswordLen: L("Password must be at least 8 characters with letters and numbers.", "পাসওয়ার্ড কমপক্ষে ৮ অক্ষরের হতে হবে — অক্ষর ও সংখ্যাসহ।"),
  errPasswordMatch: L("Passwords do not match.", "পাসওয়ার্ড দুটি মেলেনি।"),
  errMobile: L("Please enter a valid mobile number.", "সঠিক মোবাইল নম্বর লিখুন।"),

  /* Shop */
  shop: L("Shop", "শপ"),
  shopTitle: L("Digital Marketplace", "ডিজিটাল মার্কেটপ্লেস"),
  shopSub: L("Order digital services and buy premium products — checkout, wallet and invoices included.", "ডিজিটাল সার্ভিস অর্ডার ও প্রিমিয়াম প্রোডাক্ট কিনুন — চেকআউট, ওয়ালেট ও ইনভয়েসসহ।"),
  allItems: L("All", "সব"),
  products: L("Products", "প্রোডাক্ট"),
  services: L("Services", "সার্ভিস"),
  addToCart: L("Add to Cart", "কার্টে যোগ করুন"),
  orderNow: L("Order Now", "এখনই অর্ডার করুন"),
  viewDetails: L("View Details", "বিস্তারিত দেখুন"),
  searchPh: L("Search products & services…", "প্রোডাক্ট ও সার্ভিস খুঁজুন…"),
  yourCart: L("Your Cart", "আপনার কার্ট"),
  cartEmpty: L("Your cart is empty. Browse the catalog to add items.", "আপনার কার্ট খালি। আইটেম যোগ করতে ক্যাটালগ ব্রাউজ করুন।"),
  subtotal: L("Subtotal", "সাবটোটাল"),
  discount: L("Discount", "ডিসকাউন্ট"),
  total: L("Total", "মোট"),
  coupon: L("Coupon", "কুপন"),
  applyCoupon: L("Apply", "প্রয়োগ করুন"),
  checkout: L("Checkout", "চেকআউট"),
  continueShopping: L("Continue Shopping", "শপিং চালিয়ে যান"),
  paymentMethod: L("Payment Method", "পেমেন্ট মাধ্যম"),
  walletBalance: L("Wallet Balance", "ওয়ালেট ব্যালেন্স"),
  payWithWallet: L("Pay with Wallet", "ওয়ালেট দিয়ে পেমেন্ট"),
  trxId: L("Transaction ID / Reference", "ট্রানজেকশন আইডি / রেফারেন্স"),
  placeOrder: L("Place Order", "অর্ডার করুন"),
  orderSuccess: L("Order Placed Successfully", "অর্ডার সফলভাবে সম্পন্ন হয়েছে"),
  orderPendingPay: L("Payment Pending Verification", "পেমেন্ট যাচাই বাকি"),
  orderPendingPayDesc: L("Complete the payment using the selected method and share the Transaction ID. Our team will verify and activate your order.", "নির্বাচিত মাধ্যমে পেমেন্ট সম্পন্ন করে ট্রানজেকশন আইডি দিন। আমাদের টিম যাচাই করে অর্ডারটি সক্রিয় করবে।"),
  orderPaidDesc: L("Your payment is confirmed. You can track this order from your dashboard.", "আপনার পেমেন্ট নিশ্চিত হয়েছে। ড্যাশবোর্ড থেকে এই অর্ডার ট্র্যাক করতে পারবেন।"),
  requirements: L("Order Requirements", "অর্ডারের প্রয়োজনীয় তথ্য"),
  startingFrom: L("Starting from", "শুরু থেকে"),
  perYear: L("/year", "/বছর"),
  perMonth: L("/month", "/মাস"),
  licenseDownload: L("Download License", "লাইসেন্স ডাউনলোড"),
  backToShop: L("Back to Shop", "শপে ফিরে যান"),
  addRequirements: L("Fill requirements to continue", "এগিয়ে যেতে প্রয়োজনীয় তথ্য দিন"),

  /* Client portal */
  dashboard: L("Dashboard", "ড্যাশবোর্ড"),
  myOrders: L("My Orders", "আমার অর্ডার"),
  subscriptions: L("Subscriptions", "সাবস্ক্রিপশন"),
  renewals: L("Renewals", "নবায়ন"),
  wallet: L("Wallet", "ওয়ালেট"),
  addFunds: L("Add Funds", "ফান্ড যোগ করুন"),
  transactions: L("Transactions", "লেনদেন"),
  invoices: L("Invoices", "ইনভয়েস"),
  downloads: L("Downloads", "ডাউনলোড"),
  support: L("Support", "সাপোর্ট"),
  notifications: L("Notifications", "নোটিফিকেশন"),
  profile: L("Profile", "প্রোফাইল"),
  security: L("Security", "নিরাপত্তা"),
  logout: L("Logout", "লগআউট"),
  totalOrders: L("Total Orders", "মোট অর্ডার"),
  activeServices: L("Active Services", "সক্রিয় সার্ভিস"),
  activeSubs: L("Active Subscriptions", "সক্রিয় সাবস্ক্রিপশন"),
  pendingOrders: L("Pending Orders", "বাকি অর্ডার"),
  completedOrders: L("Completed Orders", "সম্পন্ন অর্ডার"),
  orderDetails: L("Order Details", "অর্ডার বিবরণ"),
  orderTimeline: L("Order Timeline", "অর্ডার টাইমলাইন"),
  addNote: L("Add Note", "নোট যোগ করুন"),
  viewInvoice: L("View Invoice", "ইনভয়েস দেখুন"),
  printInvoice: L("Print / Save PDF", "প্রিন্ট / PDF সংরক্ষণ"),
  renewNow: L("Renew Now", "এখনই নবায়ন করুন"),
  nextRenewal: L("Next renewal", "পরবর্তী নবায়ন"),
  status: L("Status", "স্ট্যাটাস"),
  date: L("Date", "তারিখ"),
  amount: L("Amount", "পরিমাণ"),
  reason: L("Reason", "কারণ"),
  depositMethods: L("Deposit Methods", "ডিপোজিট মাধ্যম"),
  chooseAmount: L("Choose an amount", "একটি পরিমাণ নির্বাচন করুন"),
  customAmount: L("Custom Amount", "কাস্টম পরিমাণ"),
  depositSuccess: L("Deposit request submitted. Our team will verify your payment and credit your wallet.", "ডিপোজিট অনুরোধ জমা হয়েছে। আমাদের টিম পেমেন্ট যাচাই করে ওয়ালেটে ক্রেডিট করবে।"),
  newTicket: L("New Ticket", "নতুন টিকিট"),
  ticketSubject: L("Subject", "বিষয়"),
  ticketCategory: L("Category", "ক্যাটাগরি"),
  ticketPriority: L("Priority", "অগ্রাধিকার"),
  ticketMessage: L("Message", "বার্তা"),
  createTicket: L("Create Ticket", "টিকিট তৈরি করুন"),
  reply: L("Reply", "উত্তর দিন"),
  changePassword: L("Change Password", "পাসওয়ার্ড পরিবর্তন"),
  currentPassword: L("Current Password", "বর্তমান পাসওয়ার্ড"),
  newPassword: L("New Password", "নতুন পাসওয়ার্ড"),
  updateProfile: L("Update Profile", "প্রোফাইল আপডেট"),
  markRead: L("Mark all read", "সব পড়া হয়েছে চিহ্নিত করুন"),

  /* Affiliate portal */
  affiliate: L("Affiliate", "এফিলিয়েট"),
  affiliatePanel: L("Affiliate Panel", "এফিলিয়েট প্যানেল"),
  applicationStatus: L("Application Status", "আবেদনের অবস্থা"),
  pendingReview: L("Pending Review", "যাচাই বাকি"),
  underReview: L("Under Review", "পর্যালোচনাধীন"),
  approved: L("Approved", "অনুমোদিত"),
  rejected: L("Rejected", "প্রত্যাখ্যাত"),
  suspended: L("Suspended", "সাময়িক বরখাস্ত"),
  active: L("Active", "সক্রিয়"),
  kycRequired: L("KYC Required", "KYC প্রয়োজন"),
  kycBanner: L("Your affiliate application is approved, but KYC verification is required before affiliate features can be activated.", "আপনার এফিলিয়েট আবেদন অনুমোদিত হয়েছে, তবে এফিলিয়েট ফিচার সক্রিয় করতে KYC যাচাই আবশ্যক।"),
  kycWaiting: L("Your KYC documents have been submitted and are under review by our team.", "আপনার KYC ডকুমেন্ট জমা হয়েছে এবং আমাদের টিম পর্যালোচনা করছে।"),
  kycRejected: L("KYC rejected. Reason:", "KYC প্রত্যাখ্যাত হয়েছে। কারণ:"),
  completeKyc: L("Complete KYC Verification", "KYC যাচাই সম্পন্ন করুন"),
  kycFullName: L("Full Name", "পূর্ণ নাম"),
  kycDob: L("Date of Birth", "জন্ম তারিখ"),
  kycAddress: L("Address", "ঠিকানা"),
  kycNid: L("NID / Passport Number", "NID / পাসপোর্ট নম্বর"),
  kycPayment: L("Payment Method for Earnings (bKash/Nagad/Bank)", "আয়ের পেমেন্ট মাধ্যম (bKash/Nagad/Bank)"),
  submitKyc: L("Submit KYC", "KYC জমা দিন"),
  kycNote: L("Documents are stored securely and reviewed only by authorized admins.", "ডকুমেন্ট নিরাপদে সংরক্ষিত হয় এবং শুধুমাত্র অনুমোদিত অ্যাডমিন পর্যালোচনা করেন।"),
  affiliateDashboard: L("Affiliate Dashboard", "এফিলিয়েট ড্যাশবোর্ড"),
  totalClicks: L("Total Clicks", "মোট ক্লিক"),
  totalReferrals: L("Referrals", "রেফারেল"),
  successfulOrders: L("Successful Orders", "সফল অর্ডার"),
  conversionRate: L("Conversion Rate", "কনভার্শন রেট"),
  pendingCommission: L("Pending Commission", "বাকি কমিশন"),
  approvedCommission: L("Approved Commission", "অনুমোদিত কমিশন"),
  paidCommission: L("Paid Commission", "পরিশোধিত কমিশন"),
  totalEarnings: L("Total Earnings", "মোট আয়"),
  availableBalance: L("Available Balance", "উপলব্ধ ব্যালেন্স"),
  catalog: L("Eligible Catalog", "যোগ্য ক্যাটালগ"),
  yourLink: L("Your Affiliate Link", "আপনার এফিলিয়েট লিংক"),
  copyLink: L("Copy Link", "লিংক কপি"),
  copied: L("Copied!", "কপি হয়েছে!"),
  shareWhatsApp: L("Share on WhatsApp", "হোয়াটসঅ্যাপে শেয়ার"),
  commission: L("Commission", "কমিশন"),
  commissions: L("Commissions", "কমিশন"),
  withdrawals: L("Withdrawals", "উইথড্রয়াল"),
  requestWithdrawal: L("Request Withdrawal", "উইথড্রয়াল অনুরোধ করুন"),
  minWithdrawal: L("Minimum withdrawal", "সর্বনিম্ন উইথড্রয়াল"),
  accountInfo: L("Account Information (bKash/Nagad/Bank)", "অ্যাকাউন্ট তথ্য (bKash/Nagad/Bank)"),
  withdrawalNote: L("Note (optional)", "নোট (ঐচ্ছিক)"),
  reports: L("Reports", "রিপোর্ট"),
  clicks: L("Clicks", "ক্লিক"),
  monthlyEarnings: L("Earnings (last 30 days)", "আয় (গত ৩০ দিন)"),
  fraudNote: L("Self-referrals and duplicate accounts are detected and flagged for review.", "সেলফ-রেফারেল ও ডুপ্লিকেট অ্যাকাউন্ট শনাক্ত করে যাচাইয়ের জন্য ফ্ল্যাগ করা হয়।"),

  /* Admin */
  adminPanel: L("Admin Panel", "অ্যাডমিন প্যানেল"),
  overview: L("Overview", "ওভারভিউ"),
  orders: L("Orders", "অর্ডার"),
  payments: L("Payments", "পেমেন্ট"),
  coupons: L("Coupons", "কুপন"),
  customers: L("Customers", "গ্রাহক"),
  affiliates: L("Affiliates", "এফিলিয়েট"),
  applications: L("Applications", "আবেদন"),
  kycReview: L("KYC Review", "KYC পর্যালোচনা"),
  content: L("Content", "কনটেন্ট"),
  settings: L("Settings", "সেটিংস"),
  admins: L("Admins & Roles", "অ্যাডমিন ও রোল"),
  logs: L("Activity Logs", "অ্যাক্টিভিটি লগ"),
  catalog2: L("Catalog", "ক্যাটালগ"),
  totalUsers: L("Total Users", "মোট ইউজার"),
  totalClients: L("Total Clients", "মোট ক্লায়েন্ট"),
  totalAffiliates: L("Total Affiliates", "মোট এফিলিয়েট"),
  pendingApps: L("Pending Applications", "বাকি আবেদন"),
  pendingKyc: L("Pending KYC", "বাকি KYC"),
  totalProducts: L("Total Products", "মোট প্রোডাক্ট"),
  totalServices: L("Total Services", "মোট সার্ভিস"),
  /* Callback requests */
  requestCallback: L("Request a Callback", "কলব্যাক রিকুয়েস্ট"),
  callbackTitle: L("Request a Callback", "কলব্যাক রিকুয়েস্ট করুন"),
  callbackSub: L("Submit your issue or question — our expert team will call you back within 24 hours.", "আপনার সমস্যা বা প্রশ্ন জমা দিন — আগামী ২৪ ঘণ্টার মধ্যে আমাদের এক্সপার্ট টিম আপনাকে কল করবে।"),
  callbackSubject: L("Subject / Issue Type", "বিষয় / সমস্যার ধরন"),
  callbackSubjects: [
    L("Order Problem", "অর্ডার সংক্রান্ত সমস্যা"),
    L("Payment Issue", "পেমেন্ট সংক্রান্ত সমস্যা"),
    L("Service Enquiry", "সার্ভিস সম্পর্কিত জানতে চাই"),
    L("Website / Technical Issue", "ওয়েবসাইট / টেকনিক্যাল সমস্যা"),
    L("Complaint", "অভিযোগ"),
    L("Other Request", "অন্যান্য অনুরোধ"),
  ],
  callbackMessage: L("Complaint / Message / Request Details", "অভিযোগ / বার্তা / অনুরোধের বিবরণ"),
  callbackTime: L("Preferred Callback Time", "পছন্দের কলব্যাক সময়"),
  callbackTimes: [
    L("Morning (9 AM – 12 PM)", "সকাল (৯টা – ১২টা)"),
    L("Afternoon (12 PM – 4 PM)", "দুপুর (১২টা – ৪টা)"),
    L("Evening (4 PM – 8 PM)", "সন্ধ্যা (৪টা – ৮টা)"),
    L("Any Time", "যেকোনো সময়"),
  ],
  callbackPriority: L("Priority", "অগ্রাধিকার"),
  callbackSubmit: L("Submit Callback Request", "কলব্যাক রিকুয়েস্ট জমা দিন"),
  callbackSuccessTitle: L("Callback Request Submitted Successfully", "আপনার কলব্যাক রিকুয়েস্টটি সফলভাবে সাবমিট হয়েছে"),
  callbackSuccessBody: L("Please wait. Our expert team will contact you within the next 24 hours.", "অনুগ্রহ করে অপেক্ষা করুন। আগামী ২৪ ঘন্টার মধ্যে আমাদের এক্সপার্ট টিম থেকে আপনার সাথে যোগাযোগ করা হবে।"),
  callbackRequestId: L("Request ID", "রিকুয়েস্ট আইডি"),
  callbackWhatsapp: L("WhatsApp Number", "হোয়াটসঅ্যাপ নম্বর"),
  callbackNew: L("Submit Another Request", "আরেকটি রিকুয়েস্ট জমা দিন"),
  callbackStatusNew: L("New", "নতুন"),
  callbackStatusPending: L("Pending", "বিচারাধীন"),
  callbackStatusInProgress: L("In Progress", "চলমান"),
  callbackStatusContacted: L("Contacted", "যোগাযোগ করা হয়েছে"),
  callbackStatusResolved: L("Resolved", "সমাধান হয়েছে"),
  callbackStatusCancelled: L("Cancelled", "বাতিল"),
  callbackAssigned: L("Assigned Staff", "দায়িত্বপ্রাপ্ত স্টাফ"),
  callbackInternalNote: L("Internal Note", "অভ্যন্তরীণ নোট"),
  callbackUpdated: L("Last Updated", "সর্বশেষ আপডেট"),
  callbackErrs: {
    subject: L("Please select an issue type.", "অনুগ্রহ করে সমস্যার ধরন নির্বাচন করুন।"),
    message: L("Please describe your issue in at least 10 characters.", "অনুগ্রহ করে কমপক্ষে ১০ অক্ষরে আপনার সমস্যা বর্ণনা করুন।"),
  },

  /* Appointments */
  appointments: L("Appointments", "অ্যাপয়েন্টমেন্ট"),
  appointmentServices: L("Appointment Services", "অ্যাপয়েন্টমেন্ট সার্ভিস"),
  appointmentIntegration: L("Appointment Integration", "অ্যাপয়েন্টমেন্ট ইন্টিগ্রেশন"),
  scheduleMeeting: L("Schedule a Meeting", "মিটিং নির্ধারণ করুন"),
  bookAppointment: L("Book an Appointment", "অ্যাপয়েন্টমেন্ট বুক করুন"),
  appointmentSub: L("Schedule a meeting with the AL-KHUBAIB IT expert team — availability is verified in real time from the central appointment system.", "AL-KHUBAIB IT এক্সপার্ট টিমের সাথে মিটিং নির্ধারণ করুন — সেন্ট্রাল অ্যাপয়েন্টমেন্ট সিস্টেম থেকে রিয়েল-টাইমে সময়ের উপলব্ধতা যাচাই করা হয়।"),
  appointmentUnavailable: L("Sorry, appointment booking is temporarily unavailable. Please try again later.", "দুঃখিত, অ্যাপয়েন্টমেন্ট বুকিং সাময়িকভাবে অনুপলব্ধ। অনুগ্রহ করে পরে আবার চেষ্টা করুন।"),
  appointmentTimeout: L("Unable to connect to the appointment service. Please try again later.", "অ্যাপয়েন্টমেন্ট সার্ভিসের সাথে সংযোগ স্থাপন করা যাচ্ছে না। অনুগ্রহ করে পরে আবার চেষ্টা করুন।"),
  loadingTimes: L("Loading available times…", "উপলব্ধ সময় লোড হচ্ছে…"),
  submittingAppointment: L("Submitting appointment…", "অ্যাপয়েন্টমেন্ট জমা হচ্ছে…"),
  selectService: L("Select Service", "সার্ভিস নির্বাচন করুন"),
  selectDate: L("Select Date", "তারিখ নির্বাচন করুন"),
  selectTime: L("Available Time", "উপলব্ধ সময়"),
  slotTaken: L("This time slot is no longer available. Please select another available time.", "এই সময়স্লটটি আর উপলব্ধ নেই। অনুগ্রহ করে অন্য একটি উপলব্ধ সময় নির্বাচন করুন।"),
  appointmentSuccess: L("Appointment Submitted Successfully", "অ্যাপয়েন্টমেন্ট সফলভাবে জমা হয়েছে"),
  appointmentStatusPending: L("Pending", "বিচারাধীন"),
  viewAppointmentStatus: L("View Appointment Status", "অ্যাপয়েন্টমেন্ট স্ট্যাটাস দেখুন"),
  noSlots: L("No available time slots on this date. Please choose another date.", "এই তারিখে কোনো উপলব্ধ সময় নেই। অন্য তারিখ নির্বাচন করুন।"),
  minutes: L("minutes", "মিনিট"),
  connected: L("Connected", "সংযুক্ত"),
  notConnected: L("Not Connected", "সংযুক্ত নয়"),
  testConnection: L("Test Connection", "সংযোগ পরীক্ষা করুন"),
  appointmentOn: L("Appointment System", "অ্যাপয়েন্টমেন্ট সিস্টেম"),
  proxyUrl: L("Portfolio API URL (server-side proxy)", "Portfolio API URL (সার্ভার-সাইড প্রক্সি)"),
  apiKey: L("API Key", "API Key"),
  apiSecret: L("API Secret", "API Secret"),
  source: L("Source", "সোর্স"),
  centralAppointmentId: L("Central Appointment ID", "সেন্ট্রাল অ্যাপয়েন্টমেন্ট আইডি"),
  integrationLogs: L("Integration Logs (request/response)", "ইন্টিগ্রেশন লগ (রিকুয়েস্ট/রেসপন্স)"),
  proxyNote: L("All requests to the central appointment system are performed server-side through the company proxy. Credentials are never exposed to the browser.", "সেন্ট্রাল অ্যাপয়েন্টমেন্ট সিস্টেমে সব রিকুয়েস্ট কোম্পানি প্রক্সির মাধ্যমে সার্ভার-সাইডে সম্পন্ন হয়। ব্রাউজারে ক্রেডেনশিয়াল কখনো প্রকাশ করা হয় না।"),

  adminPendingOrders: L("Pending Orders", "বাকি অর্ডার"),
  totalSales: L("Total Sales", "মোট বিক্রয়"),
  pendingPayments: L("Pending Payments", "বাকি পেমেন্ট"),
  totalCommission: L("Total Commission", "মোট কমিশন"),
  pendingWithdrawals: L("Pending Withdrawals", "বাকি উইথড্রয়াল"),
  verify: L("Verify", "যাচাই করুন"),
  reject: L("Reject", "প্রত্যাখ্যান"),
  approve: L("Approve", "অনুমোদন"),
  paid: L("Paid", "পরিশোধিত"),
  processing: L("Processing", "প্রসেসিং"),
  save: L("Save", "সংরক্ষণ"),
  cancel: L("Cancel", "বাতিল"),
  edit: L("Edit", "সম্পাদনা"),
  delete: L("Delete", "মুছুন"),
  addNew: L("Add New", "নতুন যোগ করুন"),
  adminSearch: L("Search…", "খুঁজুন…"),
  exportCsv: L("Export CSV", "CSV এক্সপোর্ট"),
  last30: L("Last 30 Days", "গত ৩০ দিন"),
  last7: L("Last 7 Days", "গত ৭ দিন"),
  thisYear: L("This Year", "এই বছর"),
  salesOverview: L("Sales Overview", "বিক্রয় ওভারভিউ"),
  ordersChart: L("Orders", "অর্ডার"),
  revenue: L("Revenue", "আয়"),
  adjustWallet: L("Adjust Wallet", "ওয়ালেট অ্যাডজাস্ট"),
  credit: L("Credit", "ক্রেডিট"),
  debit: L("Debit", "ডেবিট"),
  createCoupon: L("Create Coupon", "কুপন তৈরি করুন"),
  couponCode: L("Coupon Code", "কুপন কোড"),
  couponType: L("Type", "ধরন"),
  percent: L("Percentage", "শতাংশ"),
  fixed: L("Fixed Amount", "নির্দিষ্ট পরিমাণ"),
  minOrder: L("Minimum Order", "সর্বনিম্ন অর্ডার"),
  maxUses: L("Max Uses", "সর্বোচ্চ ব্যবহার"),
  expiry: L("Expiry Date", "মেয়াদ শেষের তারিখ"),
  enabled: L("Enabled", "সক্রিয়"),
  english: L("English", "English"),
  bangla: L("Bangla", "বাংলা"),
  downloadBackup: L("Download Backup", "ব্যাকআপ ডাউনলোড"),
  resetData: L("Reset All Data", "সব ডেটা রিসেট"),
  changeStatus: L("Change Status", "স্ট্যাটাস পরিবর্তন"),
  addNoteBtn: L("Add Note", "নোট যোগ করুন"),
  emailTemplates: L("Notification Settings", "নোটিফিকেশন সেটিংস"),
};

export const STATUS_TXT: Record<string, L10n> = {
  pending: L("Pending", "বিচারাধীন"),
  under_review: L("Under Review", "পর্যালোচনাধীন"),
  approved: L("Approved", "অনুমোদিত"),
  rejected: L("Rejected", "প্রত্যাখ্যাত"),
  suspended: L("Suspended", "সাময়িক বরখাস্ত"),
  active: L("Active", "সক্রিয়"),
  expired: L("Expired", "মেয়াদোত্তীর্ণ"),
  cancelled: L("Cancelled", "বাতিল"),
  refunded: L("Refunded", "ফেরত দেওয়া হয়েছে"),
  completed: L("Completed", "সম্পন্ন"),
  paid: L("Paid", "পরিশোধিত"),
  reversed: L("Reversed", "রিভার্সড"),
  processing: L("Processing", "প্রসেসিং"),
  pending_payment: L("Pending Payment", "পেমেন্ট বাকি"),
  payment_confirmed: L("Payment Confirmed", "পেমেন্ট নিশ্চিত"),
  in_progress: L("Work in Progress", "কাজ চলছে"),
  quality_check: L("Quality Check", "কোয়ালিটি চেক"),
  ready: L("Ready / Download Available", "প্রস্তুত / ডাউনলোড উপলব্ধ"),
  pending_verification: L("Pending Verification", "যাচাই বাকি"),
  verified: L("Verified", "যাচাইকৃত"),
  not_submitted: L("Not Submitted", "জমা হয়নি"),
  submitted: L("Submitted", "জমা হয়েছে"),
  resubmission_required: L("Resubmission Required", "পুনরায় জমা আবশ্যক"),
  waiting_for_customer: L("Waiting for Customer", "গ্রাহকের অপেক্ষায়"),
  open: L("Open", "খোলা"),
  in_progress_ticket: L("In Progress", "চলমান"),
  resolved: L("Resolved", "সমাধান হয়েছে"),
  closed: L("Closed", "বন্ধ"),
  unpaid: L("Unpaid", "অপরিশোধিত"),
};

export const ORDER_STATUSES = [
  "pending_payment",
  "payment_confirmed",
  "processing",
  "in_progress",
  "quality_check",
  "ready",
  "completed",
  "cancelled",
  "refunded",
] as const;
